### ISSUE TITLE
Melhorias necessárias.

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho1-Grupo4#2]
Bom dia malta.

Caso se opte, então, pela segunda versão do trabalho, proponho a seguinte divisão de tarefas:
        -> @bdppereira Penso que poderias tratar da parte de colocar os print's dos resultados (o que está na função timeout, no fundo) no formato de dicionário, visto que já tinhas feito algo semelhante na outra versão do trabalho;
        -> @DanielGadelho Penso que poderias tratar de testar o programa até ao mais pequeno detalhe, no sentido de garantir que o programa nunca dá erro e que funciona tudo como deve de ser;
        -> Eu e o @davidgermanorodrigues Poderíamos tentar pensar em mais alguma funcionalidade extra que podesse ser acrescentada ao programa.

Por favor, digam se concordam.

**Comment by bdppereira** [comment]
Ola

Aparentemente estva a trabalhar numa versão errada
fiz o preenchimento e a apresentação do dicionario mas agora ia fazer o commit e acho que não está a dar por causa das alterações do David

Isto é uma confusao, desculpem, mas não me entendo la muito bem nisto

**Comment by bruno5198** [comment]
@bdppereira Já fiz as alterações, conforme constava no programa que me envias-te por e-mail...
P.s.: A questão de não funcionar com tempo também já está resolvida, contudo de forma meia "atabalhoada". Vejam e digam alguma coisa, sff...

**Comment by bdppereira** [comment]
Obrigado
Parece Ok
