### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by bdppereira** [bruno5198/Trabalho1-Grupo4#3]
Malta: Agora penso que devemos limpar o codigo, se for possivel porque o Bruno nao brinca
e
Testar isto, para ver se funciona tudo bem e gera os resultados corretos

**Comment by bruno5198** [comment]
Acabei de acrescentar alguns comentários que estavam em falta ao programa, para que este fique minimamente legível.
Em termos de código, não fiz nenhuma alteração.

**Comment by DanielGadelho** [comment]
Viva.
No commit b6c8d12141b56be25d8df3e5802e967525736500 que eu fiz, foram feitos diversos melhoramentos ao código, nomeadamente nos comentários, resolução de warnings, algum "embelezamento" nos prints e na estrutura do código e pequenas alterações de código sem alterações funcionais.

**Comment by bruno5198** [comment]
Boas malta.
Bom trabalho Daniel, estive a dar uma vista de olhos ao código e parece-me estar impecável.
Por mim está pronto a entregar, o que acham @bdppereira @davidgermanorodrigues ?

**Comment by bdppereira** [comment]
Ola

Por mim também está pronto

**Comment by davidgermanorodrigues** [comment]
Boa noite pessoal, 
Fiz uma pequena alteração num dos prints de erros nos início do código (linhas 50 a 64).
Também acho que está pronto a entregar.
