### ISSUE TITLE
Problemas no parâmetro -mv

### ISSUE THREAD

**Issue by DanielGadelho** [bruno5198/Trabalho1-Grupo4#5]
Viva.
Ao colocar um valor de -mv negativo, torna o programa sem fim (com ou sem uso do -utm). O programa apenas terminará com o uso do stop_key ('ESPAÇO') ou com o uso do CTRL+C.

**Comment by bruno5198** [comment]
Não faz sequer sentido colocar um valor de -mv negativo, portanto é colocar um IF que apenas permita que o programa avance caso o valor de -mv seja positivo.

**Comment by DanielGadelho** [comment]
Issue #5 resolvido! Adicionada uma verificação ao parâmetro 'max_value' em que caso o valor não seja maior do que zero, é devolvida uma mensagem de erro.
